// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmhJqLjVLTsIBp3-pymRdqDCgwSHmZKM8',
    appId: '1:89187810320:web:c210b0ee19ee26ee075e95',
    messagingSenderId: '89187810320',
    projectId: 'portfolio-36040',
    authDomain: 'portfolio-36040.firebaseapp.com',
    storageBucket: 'portfolio-36040.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9w6sXEoZWy16dVCSevVHisKFo37qCZII',
    appId: '1:89187810320:android:cf72e871f2ed9b82075e95',
    messagingSenderId: '89187810320',
    projectId: 'portfolio-36040',
    storageBucket: 'portfolio-36040.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_iqdHZb-4hpxUvChsxdW2pQ5-uqkujU',
    appId: '1:89187810320:ios:6706cc7e025492b7075e95',
    messagingSenderId: '89187810320',
    projectId: 'portfolio-36040',
    storageBucket: 'portfolio-36040.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_iqdHZb-4hpxUvChsxdW2pQ5-uqkujU',
    appId: '1:89187810320:ios:6da06290b1ead50f075e95',
    messagingSenderId: '89187810320',
    projectId: 'portfolio-36040',
    storageBucket: 'portfolio-36040.appspot.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
